on:
  workflow_call:
    secrets:
      environment-secrets:
        required: false

jobs:
  test:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo "Start of reusable workflow"
          echo "${{ secrets.environment-secrets }}" | rev
          echo "End of reusable workflow"
