on:
  workflow_call:
    secrets:
      environment-secrets:
        required: true

jobs:
  test:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo ${{ inputs.environment }}
          echo ${{ inputs.environment-secrets }}