on:
  workflow_call:
    secrets:
      environment-secrets:
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo "${{ secrets.environment-secrets }}" | rev