name: test

on: workflow_dispatch

jobs:
  test:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      environment-variables: |
        TEST=${{ secrets.TEST }}
    secrets:
      environment-secrets: |
        SECRET_TEST=${{ secrets.TEST }}

