name: test

on: workflow_dispatch

env:
  TEST: workflow_env

jobs:

  environment-variables:
    runs-on: ubuntu-latest
    steps:
      - id: environment-variables
        run: |
          read -r -d '' ENV_VARS <<- EndOfEnvironmentVariables
            ENV_TEST=${{ env.TEST }}
            SECRET_TEST=${{ secrets.TEST }}
            SECRET_TEST2=${{ secrets.TEST2 }}
          EndOfEnvironmentVariables
          echo "::set-output name=environment-variables::${ENV_VARS}"
    outputs:
      environment-variables: ${{ steps.environment-variables.outputs.environment-variables }}

  test:
    needs: environment-variables
    uses: ./.github/workflows/reusable-workflow.yml
    secrets:
      environment-secrets: ${{ needs.environment-variables.outputs.environment-variables }}

